### ISSUE TITLE
new OpenAI embedding model

### ISSUE THREAD

**Issue by codeMonkey-shin** [amikos-tech/chromadb-java-client#18]
I would like to try “text-embedding-3-large”, a newly released embedding model from openai. A function that allows users to select the desired embedding model is needed.

**Comment by tazarov** [comment]
sure thing. Let me add that.

**Comment by tazarov** [comment]
@codeMonkey-shin,

Done and new version released:

```xml
<dependency>
    <groupId>io.github.amikos-tech</groupId>
    <artifactId>chromadb-java-client</artifactId>
    <version>0.1.3</version>
</dependency>
```
