### ISSUE TITLE
openai embedding custom url

### ISSUE THREAD

**Issue by codeMonkey-shin** [amikos-tech/chromadb-java-client#22]
The bge-m3 model is a local embedding model that surpasses openai's large embedding model. I would like to load this into a server compatible with openai API and use it in conjunction with chromadb. Therefore, it would be nice if users could use custom URLs when using the openai embedding feature in your project.

Thank you for your efforts,

**Comment by codeMonkey-shin** [comment]
https://github.com/michaelfeil/infinity
Please refer to the project

**Comment by tazarov** [comment]
@codeMonkey-shin, PR is up. I'll create a new release later today

**Comment by tazarov** [comment]
@codeMonkey-shin, this is now done an new version `0.1.4` is published:

https://central.sonatype.com/artifact/io.github.amikos-tech/chromadb-java-client/overview

**Comment by codeMonkey-shin** [comment]
thank you!
