### ISSUE TITLE
Socket Time Out Read Chroma + Get ALL

### ISSUE THREAD

**Issue by ntd1683** [amikos-tech/chromadb-java-client#28]
Error Socket time out , Socket closed
`Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: tech.amikos.chromadb.handler.ApiException: java.net.SocketTimeoutException: timeout] with root cause
java.net.SocketException: Socket closed`

my code : 
```
@Override
    public Set<String> getExistingIds() throws ApiException {
        Client client = new Client(System.getenv("CHROMA_URL"));
        String apiKey = System.getenv("OPENAI_API_KEY");

        System.out.println(apiKey + " " + System.getenv("CHROMA_URL"));
        System.out.println(client);
        EmbeddingFunction ef = new OpenAIEmbeddingFunction(apiKey);
        System.out.println(ef);

        Collection collection = client.getCollection(collectionName, ef);
        List<Map<String, Object>> metaData = collection.get().getMetadatas();
        return metaData.stream().map(m -> m.get("id").toString()).collect(Collectors.toSet());
    }
```

**Comment by ntd1683** [comment]
With little data, it runs normally, but with a lot of data, you will encounter the same error

**Comment by tazarov** [comment]
It might be some issue with a large number of results being processed by Okhttp lib. I'll reproduce and address it.

**Comment by tazarov** [comment]
I think adding pagination support can be an excellent approach to this.

**Comment by ntd1683** [comment]
Thank you very much, I will wait

**Comment by tazarov** [comment]
@ntd1683, I've added an API timeout which you can set using `client.setTimeout(180)`.

**Comment by ntd1683** [comment]
I think it's okay, I'll wait for release new version, thank you very much

**Comment by ntd1683** [comment]
ok, I will wait, it will help me a lot

**Comment by tazarov** [comment]
@ntd1683, all done. `0.1.5` is now released.

**Comment by tazarov** [comment]
@ntd1683, did you manage to test this with a high enough timeout that worked?

**Comment by ntd1683** [comment]
it helped me a lot thanks
