### ISSUE TITLE
How to auth

### ISSUE THREAD

**Issue by haqian555** [amikos-tech/chromadb-java-client#29]
It seems that there is no auth setting. How to set up Chromadb authentication

**Comment by tazarov** [comment]
@haqian555, you are right. Auth has not been added. I am doing a larger refactor to make the client a lot more useful that will contain a proper auth. In the meantime, I will add the ability to have headers that will contain the requisite Auth headers.

**Comment by tazarov** [comment]
@haqian555 examples of how to use Auth added in README.md - https://github.com/amikos-tech/chromadb-java-client?tab=readme-ov-file#example-auth

This functionality is now released in `0.1.5`
