### ISSUE TITLE
This will cause the inability to use $or queries during the query process. The where parameter should not be limited to only allowing Strings

### ISSUE THREAD

**Issue by maxuechaogao** [amikos-tech/chromadb-java-client#37]
![image](https://github.com/user-attachments/assets/6428a38e-f887-4e8e-ad63-cf312ffc0b2f)

This will cause the inability to use $or queries during the query process. The where parameter should not be limited to only allowing Strings

**Comment by maxuechaogao** [comment]
![image](https://github.com/user-attachments/assets/e24fbf2f-46e3-4f1e-a4a0-e0ee83226230)
We hope to lift the restriction here.

**Comment by tazarov** [comment]
@maxuechaogao, thanks so much for raising this. It is a valid concern. I will include a fix for this in the next release.

**Comment by tazarov** [comment]
@maxuechaogao, fixed this problem and added a test for it. The API is quite clunky, but working on a more robust refactor to create builders for the Where and WhereDocument conditions (will land  in `0.2.0`, hopefully next week). Until then:

```java
 Map<String, Object> where = new HashMap<>();
        List<Map<String,String>> conditions = new ArrayList<>();
        Map<String, String> condition1 = new HashMap<>();
        condition1.put("key1", "value1");
        conditions.add(condition1);
        Map<String, String> condition2 = new HashMap<>();
        condition2.put("key2", "value2");
        conditions.add(condition2);
        where.put("$or", conditions);
```
