### ISSUE TITLE
"Does it support text-embeddings-inference?"

### ISSUE THREAD

**Issue by ruoshuixuelabi** [amikos-tech/chromadb-java-client#66]
"Does it support the official documentation at https://docs.trychroma.com/integrations/hugging-face-server?"   

"Thank you."

**Comment by tazarov** [comment]
hey @ruoshuixuelabi, I implemented core Chroma. I don't think I've added the integration here. If that's something you need, it shouldn't be too complicated to make it work.

Let me test.

**Comment by tazarov** [comment]
@ruoshuixuelabi, I've tested, and HFEI was not supported. I created a PR to add support for it. I'll release a new version later today.
